In [1]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [3]:
c=[x+y for x,y in zip(a,b)]
c

[5, 7, 9]

In [4]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

## numpy is faster

In [10]:
import numpy as np
import time

limit=100000
l1=range(limit)
l2=range(limit)

a1=np.arange(limit)
a2=np.arange(limit)

start=time.time()
summation=[x+y for x,y in zip(l1,l2)]
print('List time',((time.time())-start)  * 1000)

start=time.time()
summation=a1+a2
print('numpy array time',((time.time())-start)  * 1000)

List time 13.773918151855469
numpy array time 1.894235610961914


## Sorting

In [15]:
# return the sorted array
x = np.array([[1,4],[3,1]])
out = np.sort(x, axis=1)
x.sort(axis=1)
print(out)

[[1 4]
 [1 3]]


In [22]:
# to get the indices of sorted array

import numpy as np 
  
a = np.array([9, 3, 1, 7, 4, 3, 6]) 
print(a)
b = np.argsort(a) 
print(b)
# To get sorted array using sorted indices 
# c is temp array created of same len as of b 
c = np.zeros(len(b), dtype = int) 
for i in range(0, len(b)): 
    c[i]= a[b[i]] 
print('Sorted array->', c) 


[9 3 1 7 4 3 6]
[2 1 5 4 6 3 0]
Sorted array-> [1 3 3 4 6 7 9]


In [28]:
x = np.array([[1,4,3],[3,1,2]])
out = np.argsort(x, axis=1)
print(x)
print('---------------')
print(out)

[[1 4 3]
 [3 1 2]]
---------------
[[0 2 1]
 [1 2 0]]


In [29]:
# return the indices of sorted array on multiple columns

import numpy as np 
  
a = np.array([9, 3, 1, 3, 4, 3, 6]) # First column 
b = np.array([4, 6, 9, 2, 1, 8, 7]) # Second column 
print('column a, column b') 
for (i, j) in zip(a, b): 
    print(i, ' ', j) 
  
ind = np.lexsort((b, a)) # Sort by a then by b 
print('Sorted indices->', ind) 

column a, column b
9   4
3   6
1   9
3   2
4   1
3   8
6   7
Sorted indices-> [2 3 1 5 4 6 0]


In [33]:
# return the indices of sorted array on multiple columns

import numpy as np 
  
a = np.array([9, 3, 1, 3, 4, 3, 6]) # First column 
b = np.array([4, 6, 9, 2, 1, 8, 7]) # Second column 
c=  np.array([3, 1, 5, 3, 7, 9, 0]) # third column
print('column a, column b') 
for (i, j, k) in zip(a, b,c): 
    print(i, ' ', j,' ',k) 
  
ind = np.lexsort((b, a,c)) # Sort by a then by b 
print('Sorted indices->', ind) 

column a, column b
9   4   3
3   6   1
1   9   5
3   2   3
4   1   7
3   8   9
6   7   0
Sorted indices-> [6 1 3 0 2 4 5]


## Searching

In [37]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)
print("maximum values =", np.max(x, 1))
print("max indices =", np.argmax(x, 1))
print("minimum values =", np.min(x, 1))
print("min indices =", np.argmin(x, 1))


x = [[9 6 2 1 4]
 [5 3 7 8 0]]
maximum values = [9 8]
max indices = [0 3]
minimum values = [1 0]
min indices = [3 4]


In [42]:
x = np.array([[np.nan, 4], [3, 2]])
print("maximum values ignoring NaNs =", np.nanmax(x, 1))
print("max indices =", np.nanargmax(x, 1))
print("minimum values ignoring NaNs =", np.nanmin(x, 1))
print("min indices =", np.nanargmin(x, 1))

maximum values ignoring NaNs = [4. 3.]
max indices = [1 0]
minimum values ignoring NaNs = [4. 2.]
min indices = [1 1]


## Counting

In [43]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
print(np.count_nonzero(x))


5


## String

In [44]:
# Concatenate

x1 = np.array(['Hello', 'Say'], dtype=np.str)
x2 = np.array([' world', ' something'], dtype=np.str)
out = np.char.add(x1, x2)
print(out)

['Hello world' 'Say something']


In [46]:
x = np.array(['heLLo woRLd', 'Say sOmething'], dtype=np.str)
capitalized = np.char.capitalize(x)
lowered = np.char.lower(x)
uppered = np.char.upper(x)
swapcased = np.char.swapcase(x)
titlecased = np.char.title(x)
print("capitalized =", capitalized)
print("lowered =", lowered)
print("uppered =", uppered)

capitalized = ['Hello world' 'Say something']
lowered = ['hello world' 'say something']
uppered = ['HELLO WORLD' 'SAY SOMETHING']


In [47]:
x = np.array(['hello world', 'say something'], dtype=np.str)
out = np.char.join(" ", x)
print(out)

['h e l l o   w o r l d' 's a y   s o m e t h i n g']


In [50]:
x = np.array(['Hello my name is John'], dtype=np.str)
out = np.char.split(x)
print(out)

[list(['Hello', 'my', 'name', 'is', 'John'])]
