In [1]:
#Create Numpy Array

In [2]:
from numpy import array

In [10]:
l=[1.0,2.0,3.0]
type(l)

list

In [5]:
a=array(l)

In [9]:
a
a.dtype

dtype('float64')

In [8]:
type(a)
a.shape

(3,)

In [17]:
#functions to create Arrays
# 1. Empty
# 2. Zeros
# 3. Ones

In [15]:
#create empty array
from numpy import empty
a=empty([3,2])

In [16]:
a

array([[6.91509441e-310, 4.68790688e-310],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [19]:
#create zero array
from numpy import zeros
a=zeros([3,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
#create one array
from numpy import ones
a=ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
b=ones(3)
b

array([1., 1., 1.])

In [25]:
#Combining Arrays
# 1. Vertical Stack
# 2. Horizontal Stack

In [38]:
#create array with vstack
from numpy import array
from numpy import vstack
#first array
a1=array([[1,4,6,7],
          [3,1,6,2]])
#second array
a2=array([2,5,8,3])
#vertical stack
a3=vstack((a1,a2))
a3

array([[1, 4, 6, 7],
       [3, 1, 6, 2],
       [2, 5, 8, 3]])

In [31]:
a1.shape

(4,)

In [32]:
a3.shape

(2, 4)

In [37]:
#create array with hstack
from numpy import array
from numpy import hstack
#first array
a1=array([[1,4,6,7],
          [1,2,3,4]])
#second array
a2=array([[2,5,8],
          [4,3,5]])
#horizontal stack
a3=hstack((a1,a2))
a3

array([[1, 4, 6, 7, 2, 5, 8],
       [1, 2, 3, 4, 4, 3, 5]])

In [50]:
#Array one dimensional indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])
print(data[1:3])
print(data[-3:])
print(data[-4:-2])

55
11
[22 33]
[33 44 55]
[22 33]


In [55]:
# index two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])
print(data[0,:])
print(data[:,0])
print(data[-1,0])
print(data[-2:,:])

11
[11 22]
[11 33 55]
55
[[33 44]
 [55 66]]


In [59]:
#two dimensional array slicing usage
# 1. Split Input and Output Features
# 2. Split Train and Test Rows

In [57]:
#Split input and Output Features

It is common to split your loaded data into input variables (X) and the output variable (y). We
can do this by slicing all rows and all columns up to, but before the last column, then separately
indexing the last column. For the input features, we can select all rows and all columns except
the last one by specifying : for in the rows index, and :-1 in the columns index.

X=[:,:-1]

For the output column, we can select all rows again using : and index just the last column
by specifying the -1 index.

Y=[:,-1]

In [58]:
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
X,y=data[:,:-1], data[:,-1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [60]:
#Split Train and Test Rows

It is common to split a loaded dataset into separate train and test sets. This is a splitting of
rows where some portion will be used to train the model and the remaining portion will be used
to estimate the skill of the trained model. This would involve slicing all columns by specifying :
in the second dimension index. The training dataset would be all rows from the beginning to
the split point.


train = data[:split, :]

The test dataset would be all rows starting from the split point to the end of the dimension.

test = data[split:, :]


In [61]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test=data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [62]:
#Array Reshaping
# 1. Data Shape
# 2. Reshape 1D to 2D array
# 3. Reshape 2D to 3D array

In [63]:
#Data Shape
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(5,)
(3, 2)


In [65]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
        [55, 66]]
# array of data
data = array(data)
print( ' Rows: %d ' % data.shape[0])
print( ' Cols: %d ' % data.shape[1])

 Rows: 3 
 Cols: 2 


In [76]:
#Reshape 1D to 2D array
# data = data.reshape((data.shape[0], 1))

# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1)) #arguement is a tuple
print(data)
print(data.shape)

(5,)
[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [78]:
#Reshape 2D to 3D array
#data.reshape((data.shape[0], data.shape[1], 1))

# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))  #arguement is a tuple
print(data)
print(data.shape)

(3, 2)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
(3, 2, 1)


In [79]:
#Numpy Array Broadcasting

Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic. A
way to overcome this is to duplicate the smaller array so that it has the dimensionality and
size as the larger array. This is called array broadcasting and is available in NumPy when
performing array arithmetic, which can greatly reduce and simplify your code.

In [80]:
#Broadcasting in Numpy

# Scalar and One dimensional Array

  a=[a1,a2,a3]
  
  b
  
The scalar will need to be broadcast across the one-dimensional array by duplicating the
value it 2 more times.
  b=[b1,b2,b3]
  
 The two one-dimensional arrays can then be added directly
 
 c=a+b
 
 c=[a1+b1,a2+b2,a3+b3]
 

In [81]:
#broadcast scalar to one-dimensional array
from numpy import array
a=array([1,2,4])
print(a)
#define scalar
b=2
print(b)
#broadcast b
c=a+b
print(c)

[1 2 4]
2
[3 4 6]


# Scalar and two-dimensional array

a=[[a11,a12,a13],
   [a21,a22,a23]]

The scalar will need to be broadcast across each row of the two-dimensional array by
duplicating it 5 more times.

b=[[b11,b12,b13],
    [b21,b22,b23]]

The two two-dimensional arrays can then be added directly.

c=a+b

c=[[a11+b11,a12+b12,a13,b13],
   [a21+b21,a22+b22,a23+b23]]


In [82]:
#broadcast scalar to two-dimensional array
from numpy import array
#define array
a=array([[1,3,5],
        [2,4,6]])
print(a)
#define scalar
b=2
print(b)
#broadcast b
c=a+b
print(c)

[[1 3 5]
 [2 4 6]]
2
[[3 5 7]
 [4 6 8]]


# One dimensional and two dimensional arrays

a=[[a11,a12,a13],
   [a21,a22,a23]]

one dimensional array b=([b1,b2,b3])

The one-dimensional array is broadcast across each row of the two-dimensional array by
creating a second copy to result in a new two-dimensional array B.


b=[[b11,b12,b13],
    [b21,b22,b23]]

The two two-dimensional arrays can then be added directly.

c=a+b

c=[[a11+b11,a12+b12,a13,b13],
   [a21+b21,a22+b22,a23+b23]]

In [84]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define one-dimensional array
b = array([2, 3, 4])
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [4 5 6]]
[2 3 4]
[[ 3  5  7]
 [ 6  8 10]]
