In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(3,)

In [6]:
a[0],a[1]

(1, 2)

In [7]:
a[1]=5

In [8]:
a

array([1, 5, 3])

In [9]:
b=np.array([[2,7,9],
            [5,1,3]])

In [10]:
b

array([[2, 7, 9],
       [5, 1, 3]])

In [13]:
b[0,1],b[-1,1],b[:,1:3]

(7, 1, array([[7, 9],
        [1, 3]]))

In [14]:
b.shape

(2, 3)

In [15]:
b.size

6

In [24]:
np.arange(7,27,2)

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [28]:
np.random.random((4,6))

array([[0.92716019, 0.87343561, 0.23781937, 0.36247143, 0.171854  ,
        0.57228481],
       [0.92098463, 0.44805904, 0.10273619, 0.08260811, 0.81448952,
        0.98444208],
       [0.51600175, 0.2997801 , 0.42882733, 0.79430339, 0.32493627,
        0.50397721],
       [0.45406141, 0.22126956, 0.26071967, 0.57571778, 0.38085028,
        0.87569974]])

In [30]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.full((4,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [35]:
np.linspace(1,2,5) # 5 values spaced evenly between, and including, 1 and 2.


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [40]:
c=np.empty([2,4])
c

array([[6.92481021e-310, 4.68657911e-310, 2.37663529e-312,
        2.56761491e-312],
       [1.93101617e-312, 9.33678148e-313, 1.97345609e-312,
        2.02566915e-322]])

In [38]:
c[1,2]

1.973456085855e-312

In [68]:
np.array([2,4],ndmin=3) # minimum dimension

array([[[2, 4]]])

In [43]:
np.dtype(np.int64)

dtype('int64')

In [45]:
np.dtype('i4')

dtype('int32')

In [48]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a.shape

(2, 3)

In [63]:
c=a.reshape((3,2))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a.ndim

2

In [64]:
c.ndim # c.ndim=len(c.shape)

2

In [71]:
np.array([2,4],ndmin=3).shape # ndmin= minimum dimension

(1, 1, 2)

In [73]:
np.array([2,4],ndmin=3).ndim # ndmin= minimum dimension

3

In [75]:
np.array([[1,2,3],[4,5,6]]).itemsize # length of each element in bytes

8

In [76]:
np.array([2,8,9],dtype=np.int8).itemsize 

1

In [77]:
np.array([2,8,9],dtype=np.int32).itemsize 

4

In [78]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [79]:
a[:2,1:3]

array([[2, 3],
       [5, 6]])

In [82]:
a[2,2]

9

In [83]:
d=np.array([[1,2,3],[4,5,0],[3,1,7]])
boolean=(d>3)

In [84]:
boolean

array([[False, False, False],
       [ True,  True, False],
       [False, False,  True]])

In [86]:
e=a[boolean]
e

array([4, 5, 9])

In [87]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4],[5,6,7]])

In [88]:
a+b

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [92]:
np.add(a,b)

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [90]:
b-a

array([[1, 1, 1],
       [1, 1, 1]])

In [94]:
np.subtract(b,a)

array([[1, 1, 1],
       [1, 1, 1]])

In [95]:
np.multiply(a,b)

array([[ 2,  6, 12],
       [20, 30, 42]])

In [96]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [97]:
np.sum(a)

21

In [98]:
np.sum(a,axis=0)  # sum of each column

array([5, 7, 9])

In [99]:
np.sum(a,axis=1)  # sum of each row

array([ 6, 15])

In [100]:
a.T               # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
a.shape

(2, 3)

In [102]:
np.array([1,2,3]).T

array([1, 2, 3])

In [104]:
np.array([1,2]).shape

(2,)

In [105]:
x=np.array([[1,2],[3,4]])
v=np.array([9,10])
x.dot(v)

array([29, 67])